### ISSUE TITLE
Models from UW3 training?

### ISSUE THREAD

**Issue by haunma** [Calamari-OCR/calamari_models#1]
Is there a place where we can find the models that were trained in the published paper?  Or must we perform training ourselves if we wish to use calamari on modern text?

**Comment by chreul** [comment]
the "antiqua_modern" folder contains a voting ensemble trained on the UW3 dataset

**Comment by haunma** [comment]
Ah, thanks!  Because "Antiqua Modern" is the name of a font, I erroneously assumed the model in that directory was trained exclusively on that font.

**Comment by lynx97** [comment]
> the "antiqua_modern" folder contains a voting ensemble trained on the UW3 dataset

I could not download UW3 dataset on the Internet. Could you please upload on drive and share it for me?
Thank you.
