### ISSUE TITLE
recommended way to download models

### ISSUE THREAD

**Issue by bertsky** [Calamari-OCR/calamari_models#11]
Short of cloning the entire repo or clicking on each individual checkpoint HDF5 and JSON file, is there a simple way to download models individually from this site? (Ideally one that can also be scripted...)

Or could you try to make GH release archives from them?

**Comment by kba** [comment]
> Or could you try to make GH release archives from them?

I second GH releases for this. That has the added advantage that the URL changes for every new release, which helps us keeping the models up-to-date using the OCR-D resource management mechanism.

This was already discussed [in 2019](https://github.com/Calamari-OCR/calamari/issues/64) in the calamari repo.

**Comment by bertsky** [comment]
@chreul @ChWick creating release archives could be as simple as:

    git checkout 2.0
    zip -9vr gt4histocr.zip gt4histocr/
    ...
    gh release -R Calamari-OCR/calamari_models upload 2.0 *.zip
    rm *.zip
    git checkout 1.1
    zip -9vr gt4histocr.zip gt4histocr/
    ...
    gh release -R Calamari-OCR/calamari_models upload 1.1 *.zip

I can do it for you if you invite me as collaborator.

**Comment by bertsky** [comment]
thx @chreul – done for all releases!

btw, if you invite me to calamari_models_experimental as well, then I'll do releases+assets there, too
