### ISSUE TITLE
fraktur_19th_century vs github.com/qurator-spk/train-calamari-gt4histocr

### ISSUE THREAD

**Issue by jbarth-ubhd** [Calamari-OCR/calamari_models#3]
Dear reader,
do you have any details about the model in fraktur_19th_century? 

Is it based on gt4histocr ground truth?

Kind regards.

**Comment by chreul** [comment]
it is mainly based on gt4histocr GT but also on Fraktur19 data from other freely available sources ([archiscribe](https://github.com/jbaiter/archiscribe-corpus) and [jze](https://github.com/jze/ocropus-model_fraktur)).
the following training pipeline was applied: each voter used a different out-of-domain mixed model as a starting point (trained on various subsets of gt4histocr). then, after training on all available Fraktur19 data using data augmentation, a final refinement step was performed, limiting the number of lines per source to a maximum of 50.
a padding of 3 rows of white pixels was added to the top and bottom of each line, if not already present. the effect on lines segmented without this padding has not been thoroughly evaluated, yet. maybe training a new/additional ensemble using no/mixed padding would be sensible. feedback would be dearly appreciated.

**Comment by jbarth-ubhd** [comment]
Thanks!
Just trying it... but it seems to take forever:
```
12:38:15.117 INFO ocrd.task_sequence.run_tasks - Start processing task 'calamari
-recognize -I OCR-D-N11 -O OCR-D-OCR -p {"checkpoint":"/usr/local/ocrd_models/ca
lamari/calamari_models/fraktur_19th_century/*.ckpt.json"}'
12:38:16.414 INFO ocrd.workspace_validator - input_file_grp=['OCR-D-N11'] output
_file_grp=['OCR-D-OCR']
Upgrading from version 2
Upgrading from version 3
Upgrading from version 4
Upgrading from version 5
Upgrading from version 6
Upgrading from version 7
Upgrading from version 8
...
...
Upgrading from version 1738637
Upgrading from version 1738638
Upgrading from version 1738639
```
now aborting... what I've done wrong?
