### ISSUE TITLE
uw3-modern-english = antiqua_modern (1.0.zip)

### ISSUE THREAD

**Issue by jbarth-ubhd** [Calamari-OCR/calamari_models#8]
Thanks for renaming antiqua_modern to uw3-modern-english, because model seems to miss some accented characters. Example:

https://digi.hadw-bw.de/view/di016/0032

»Grabstein eines Hildebertus. Urspriinglich in der Peterskirche ...«

Is there a calamari model for modern antiqua fonts & german?

**Comment by maxnth** [comment]
>Is there a calamari model for modern antiqua fonts & german?

Using the `idiotikon` model from this repository might be worthwhile. 
<details>
  <summary>Model description</summary>
<b>idiotikon</b> originated from a cooperation with Schweizerisches Idiotikon in an effort to OCR the entire dictionary. The model is based on the UW3 model and its codec contains a wide variety of mostly Latin-based characters including many diacritics. Consequently, it may be a good choice to recognize many modern languages.
</details>
