### ISSUE TITLE
GT4HistOCR models

### ISSUE THREAD

**Issue by uvius** [Calamari-OCR/calamari_models#9]
"The current model gt4histocr was trained on the entire GT4HistOCR corpus."

A combined model spanning all subcorpora of GT4HistOCR is not a good idea for several reasons:

1. The subcorpora used different transcription guidelines (labeling similar-looking glyphs with different Unicode characters). The resulting model will therefore get confused about these glyphs.
2. The size of the subcorpora is vastly different. Currently the bulk is made up 19th c. Fraktur and this will dominate the model and may even crowd out the learning of comparably rare glyphs in the smaller subcorpora.
3. The quality of the subcorpora (i.e., the remaining errors in ground truth) are also widely different. The incunabula and early modern Latin corpus have been checked much more carefully than others.

For these reasons it is a much better idea to train separate models for the subcorpora.

**Comment by chreul** [comment]
i am aware of this and fully agree with the concerns expressed. the model was mainly trained and added for the sake of completeness.
for more recent mixed models like [lsh3](https://github.com/Calamari-OCR/calamari_models_experimental) we apply a Calamari regularisation profile (work in progress) before training to harmonize the GT and deploy a training pipeline which first trains on all available GT and then performs a refinement step on selected pages/lines to enforce a more general model.
